config/routes.rb
Rails.application.routes.draw do
  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'
  mount ActionCable.server, at: '/cable'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: :true
  scope :current_display, -> { order(:created_at).last(10) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, uniqueness: true, presence: true, length: { minimum: 3, maximum: 15 }
  has_many :messages
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user 
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in? 
      flash[:error] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user

  def index 
    @message = Message.new
    @messages = Message.current_display
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create 
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast "chatroom_channel", 
                                    message: message_render(message)
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: {message: message})
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]

  def new
    
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id 
      flash[:success] = "You have logged in"
      redirect_to root_path
    else
      flash[:error] = "Something went wrong with your login info"
      render 'new'
    end
  end

  def destroy 
    session[:user_id] = nil 
    flash[:success] = "You have logged out"
    redirect_to login_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:error] = "You are already logged in"
      redirect_to root_path
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new 
    @user = User.new 
  end

  def create 
    @user = User.new(user_params)
    if @user.save 
      flash[:success] = "Welcome to chattr, #{@user.username}"
      session[:user_id] = @user.id 
      redirect_to root_path
    else 
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chatroom/index.html.erb
<div class="container mb-10">
  <h1 class="mx-auto d-block text-center">
    chattr
  </h1>
</div>
<div class="container">
  <div class="row">
    <div class="container col-12 bg-light">
     <h4 class="text-center mt-2"> chatroom </h4>
      <div class="chat-body flex-column">
        <div class="chat-card card" id="messages">
          <div class="container" id="message-container">
            <%= render @messages %>
          </div>
      </div>
      <div class="card mt-5 message-submit bg-info">
          <div class="container">
          <%= form_for(@message, html: {class: "form-inline", role: "form"}, url: message_path, remote: true) do |f| %>
            <div class="form-group col-sm-10">
              <%= f.text_field :body, placeholder: "Message", class: "form-control col-sm-12", html: {onfocus: "this.value=''"} %>
            </div>
              <%= f.button "Submit", class: "btn btn-dark"%>
            <% end %>
          </div>
        </div>
    </div>
  </div>
  
  </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message_content| %>
  <div class="alert alert-secondary">
    <i class="close icon"></i>
    <div class="header">
      <%= message_content %>
    </div>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <span class="navbar-brand" href="#">chattr</span>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
           <%= link_to "Chatroom", root_path, class: "nav-link"%>
          </li>
        </ul>
      </div>
      <ul class="navbar-nav">
        <li class="nav-item push dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Account
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <% if logged_in? %>
              <%= link_to "Log out", logout_path, method: :delete, class: "dropdown-item"%>
            <% else %>
              <%= link_to "Log in", login_path, class: "dropdown-item"%>
            <%= link_to "Register", signup_path, class: "dropdown-item"%>
            <% end %>      
          </div>
        </li>
      </ul>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chattr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'custom', media: 'all', 'data-turbolinks-track': 'reload'%>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <br/>
    <div class="container">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="card">
  <div class="card-body message row">
    <div class="col-3 message-name text-secondary">
      <%= message.user.username %>
    </div>
    <div class="col-9 message-body">
      <%= message.body %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1 class="text-center">Register for chattr</h1>
<div class="container">
  <div class='row'>
    <div class='col-sm-12'>
        <div class="card bg-light">
          <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}, url: signup_path) do |f| %>
          <div class="form-group">
              <div class="control-label col-sm-6">
                <%= f.label :username %>
              </div>
            <div class="col-sm-8">
              <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
            </div>
          </div>
          <div class="form-group">
            <div class="control-label col-sm-6">
              <%= f.label :password %>
            </div>
            <div class="col-sm-8">
              <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <%= f.submit "Register", class: 'btn btn-primary btn-lg' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>